module Evergreen.Migrate.V109 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Evergreen.V107.Notebook.Book
import Evergreen.V107.Notebook.Cell
import Evergreen.V107.Notebook.DataSet
import Evergreen.V107.Notebook.Types
import Evergreen.V107.Types
import Evergreen.V107.User
import Evergreen.V109.Notebook.Book
import Evergreen.V109.Notebook.Cell
import Evergreen.V109.Notebook.DataSet
import Evergreen.V109.Notebook.Types
import Evergreen.V109.Types
import Evergreen.V109.User
import Lamdera.Migrations exposing (..)
import List
import Maybe


frontendModel : Evergreen.V107.Types.FrontendModel -> ModelMigration Evergreen.V109.Types.FrontendModel Evergreen.V109.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V107.Types.BackendModel -> ModelMigration Evergreen.V109.Types.BackendModel Evergreen.V109.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V107.Types.FrontendMsg -> MsgMigration Evergreen.V109.Types.FrontendMsg Evergreen.V109.Types.FrontendMsg
frontendMsg old =
    MsgUnchanged


toBackend : Evergreen.V107.Types.ToBackend -> MsgMigration Evergreen.V109.Types.ToBackend Evergreen.V109.Types.BackendMsg
toBackend old =
    MsgMigrated ( migrate_Types_ToBackend old, Cmd.none )


backendMsg : Evergreen.V107.Types.BackendMsg -> MsgMigration Evergreen.V109.Types.BackendMsg Evergreen.V109.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V107.Types.ToFrontend -> MsgMigration Evergreen.V109.Types.ToFrontend Evergreen.V109.Types.FrontendMsg
toFrontend old =
    MsgMigrated ( migrate_Types_ToFrontend old, Cmd.none )


migrate_Types_FrontendModel : Evergreen.V107.Types.FrontendModel -> Evergreen.V109.Types.FrontendModel
migrate_Types_FrontendModel old =
    { key = old.key
    , url = old.url
    , messages = old.messages |> List.map migrate_Types_Message
    , appState = old.appState |> migrate_Types_AppState
    , appMode = old.appMode |> migrate_Types_AppMode
    , currentTime = old.currentTime
    , tickCount = old.tickCount
    , clockState = old.clockState |> migrate_Types_ClockState
    , pressedKeys = old.pressedKeys
    , randomSeed = old.randomSeed
    , randomProbabilities = old.randomProbabilities
    , probabilityVectorLength = old.probabilityVectorLength
    , messageId = old.messageId
    , users = old.users
    , inputName = old.inputName
    , inputIdentifier = old.inputIdentifier
    , inputAuthor = old.inputAuthor
    , inputDescription = old.inputDescription
    , inputComments = old.inputComments
    , inputData = old.inputData
    , inputCommand = old.inputCommand
    , inputPackages = old.inputPackages
    , inputInitialStateValue = old.inputInitialStateValue
    , publicDataSetMetaDataList = old.publicDataSetMetaDataList
    , privateDataSetMetaDataList = old.privateDataSetMetaDataList
    , includedCells = []
    , errorReports = old.errorReports |> List.map migrate_Notebook_Types_ErrorReport
    , showErrorPanel = old.showErrorPanel
    , theme = old.theme |> migrate_Notebook_Book_Theme
    , evalState = old.evalState |> migrate_Notebook_Types_EvalState
    , packagesFromCompiler = old.packagesFromCompiler
    , packageDict = old.packageDict
    , elmJsonError = old.elmJsonError
    , kvDict = old.kvDict
    , books = old.books |> List.map migrate_Notebook_Book_Book
    , currentCell = old.currentCell |> Maybe.map migrate_Notebook_Cell_Cell
    , cellInsertionDirection = old.cellInsertionDirection |> migrate_Notebook_Types_CellDirection
    , currentBook = old.currentBook |> migrate_Notebook_Book_Book
    , cellContent = old.cellContent
    , currentCellIndex = old.currentCellIndex
    , cloneReference = old.cloneReference
    , deleteNotebookState = old.deleteNotebookState |> migrate_Types_DeleteNotebookState
    , showNotebooks = old.showNotebooks |> migrate_Types_ShowNotebooks
    , signupState = old.signupState |> migrate_Types_SignupState
    , currentUser = old.currentUser
    , inputUsername = old.inputUsername
    , inputSignupUsername = old.inputSignupUsername
    , inputEmail = old.inputEmail
    , inputRealname = old.inputRealname
    , inputPassword = old.inputPassword
    , inputPasswordAgain = old.inputPasswordAgain
    , inputTitle = old.inputTitle
    , windowWidth = old.windowWidth
    , windowHeight = old.windowHeight
    , popupState = old.popupState |> migrate_Types_PopupState
    , showEditor = old.showEditor
    }


migrate_Notebook_Book_Book : Evergreen.V107.Notebook.Book.Book -> Evergreen.V109.Notebook.Book.Book
migrate_Notebook_Book_Book old =
    { id = old.id
    , dirty = old.dirty
    , slug = old.slug
    , origin = old.origin
    , author = old.author
    , createdAt = old.createdAt
    , updatedAt = old.updatedAt
    , public = old.public
    , title = old.title
    , cells = old.cells |> List.map migrate_Notebook_Cell_Cell
    , currentIndex = old.currentIndex
    , packageNames = old.packageNames
    , tags = old.tags
    , options = old.options
    }


migrate_Notebook_Book_Theme : Evergreen.V107.Notebook.Book.Theme -> Evergreen.V109.Notebook.Book.Theme
migrate_Notebook_Book_Theme old =
    case old of
        Evergreen.V107.Notebook.Book.DarkTheme ->
            Evergreen.V109.Notebook.Book.DarkTheme

        Evergreen.V107.Notebook.Book.LightTheme ->
            Evergreen.V109.Notebook.Book.LightTheme


migrate_Notebook_Cell_Cell : Evergreen.V107.Notebook.Cell.Cell -> Evergreen.V109.Notebook.Cell.Cell
migrate_Notebook_Cell_Cell old =
    { index = old.index
    , text = old.text
    , tipe = old.tipe |> migrate_Notebook_Cell_CellType
    , value = old.value |> migrate_Notebook_Cell_CellValue
    , cellState = old.cellState |> migrate_Notebook_Cell_CellState
    , locked = old.locked
    , report = old.report |> Tuple.mapSecond (Maybe.map (List.map migrate_Notebook_Types_MessageItem))
    , replData = old.replData
    }


migrate_Notebook_Cell_CellState : Evergreen.V107.Notebook.Cell.CellState -> Evergreen.V109.Notebook.Cell.CellState
migrate_Notebook_Cell_CellState old =
    case old of
        Evergreen.V107.Notebook.Cell.CSEdit ->
            Evergreen.V109.Notebook.Cell.CSEdit

        Evergreen.V107.Notebook.Cell.CSView ->
            Evergreen.V109.Notebook.Cell.CSView


migrate_Notebook_Cell_CellType : Evergreen.V107.Notebook.Cell.CellType -> Evergreen.V109.Notebook.Cell.CellType
migrate_Notebook_Cell_CellType old =
    case old of
        Evergreen.V107.Notebook.Cell.CTCode ->
            Evergreen.V109.Notebook.Cell.CTCode

        Evergreen.V107.Notebook.Cell.CTMarkdown ->
            Evergreen.V109.Notebook.Cell.CTMarkdown


migrate_Notebook_Cell_CellValue : Evergreen.V107.Notebook.Cell.CellValue -> Evergreen.V109.Notebook.Cell.CellValue
migrate_Notebook_Cell_CellValue old =
    case old of
        Evergreen.V107.Notebook.Cell.CVString p0 ->
            Evergreen.V109.Notebook.Cell.CVString p0

        Evergreen.V107.Notebook.Cell.CVMarkdown p0 ->
            Evergreen.V109.Notebook.Cell.CVMarkdown p0

        Evergreen.V107.Notebook.Cell.CVNone ->
            Evergreen.V109.Notebook.Cell.CVNone


migrate_Notebook_DataSet_DataSet : Evergreen.V107.Notebook.DataSet.DataSet -> Evergreen.V109.Notebook.DataSet.DataSet
migrate_Notebook_DataSet_DataSet old =
    old


migrate_Notebook_DataSet_DataSetMetaData : Evergreen.V107.Notebook.DataSet.DataSetMetaData -> Evergreen.V109.Notebook.DataSet.DataSetMetaData
migrate_Notebook_DataSet_DataSetMetaData old =
    old


migrate_Notebook_Types_CellDirection : Evergreen.V107.Notebook.Types.CellDirection -> Evergreen.V109.Notebook.Types.CellDirection
migrate_Notebook_Types_CellDirection old =
    case old of
        Evergreen.V107.Notebook.Types.Up ->
            Evergreen.V109.Notebook.Types.Up

        Evergreen.V107.Notebook.Types.Down ->
            Evergreen.V109.Notebook.Types.Down


migrate_Notebook_Types_ErrorReport : Evergreen.V107.Notebook.Types.ErrorReport -> Evergreen.V109.Notebook.Types.ErrorReport
migrate_Notebook_Types_ErrorReport old =
    old |> Tuple.mapSecond (List.map migrate_Notebook_Types_MessageItem)


migrate_Notebook_Types_EvalState : Evergreen.V107.Notebook.Types.EvalState -> Evergreen.V109.Notebook.Types.EvalState
migrate_Notebook_Types_EvalState old =
    old


migrate_Notebook_Types_MessageItem : Evergreen.V107.Notebook.Types.MessageItem -> Evergreen.V109.Notebook.Types.MessageItem
migrate_Notebook_Types_MessageItem old =
    case old of
        Evergreen.V107.Notebook.Types.Plain p0 ->
            Evergreen.V109.Notebook.Types.Plain p0

        Evergreen.V107.Notebook.Types.Styled p0 ->
            Evergreen.V109.Notebook.Types.Styled (p0 |> migrate_Notebook_Types_StyledString)


migrate_Notebook_Types_StyledString : Evergreen.V107.Notebook.Types.StyledString -> Evergreen.V109.Notebook.Types.StyledString
migrate_Notebook_Types_StyledString old =
    old


migrate_Types_AppMode : Evergreen.V107.Types.AppMode -> Evergreen.V109.Types.AppMode
migrate_Types_AppMode old =
    case old of
        Evergreen.V107.Types.AMWorking ->
            Evergreen.V109.Types.AMWorking

        Evergreen.V107.Types.AMEditTitle ->
            Evergreen.V109.Types.AMEditTitle


migrate_Types_AppState : Evergreen.V107.Types.AppState -> Evergreen.V109.Types.AppState
migrate_Types_AppState old =
    case old of
        Evergreen.V107.Types.Loading ->
            Evergreen.V109.Types.Loading

        Evergreen.V107.Types.Loaded ->
            Evergreen.V109.Types.Loaded


migrate_Types_ClockState : Evergreen.V107.Types.ClockState -> Evergreen.V109.Types.ClockState
migrate_Types_ClockState old =
    case old of
        Evergreen.V107.Types.ClockRunning ->
            Evergreen.V109.Types.ClockRunning

        Evergreen.V107.Types.ClockStopped ->
            Evergreen.V109.Types.ClockStopped

        Evergreen.V107.Types.ClockPaused ->
            Evergreen.V109.Types.ClockPaused


migrate_Types_DataSetDescription : Evergreen.V107.Types.DataSetDescription -> Evergreen.V109.Types.DataSetDescription
migrate_Types_DataSetDescription old =
    case old of
        Evergreen.V107.Types.PublicDatasets ->
            Evergreen.V109.Types.PublicDatasets

        Evergreen.V107.Types.UserDatasets p0 ->
            Evergreen.V109.Types.UserDatasets p0


migrate_Types_DeleteNotebookState : Evergreen.V107.Types.DeleteNotebookState -> Evergreen.V109.Types.DeleteNotebookState
migrate_Types_DeleteNotebookState old =
    case old of
        Evergreen.V107.Types.WaitingToDeleteNotebook ->
            Evergreen.V109.Types.WaitingToDeleteNotebook

        Evergreen.V107.Types.CanDeleteNotebook ->
            Evergreen.V109.Types.CanDeleteNotebook


migrate_Types_Message : Evergreen.V107.Types.Message -> Evergreen.V109.Types.Message
migrate_Types_Message old =
    { id = old.id
    , txt = old.txt
    , status = old.status |> migrate_Types_MessageStatus
    }


migrate_Types_MessageStatus : Evergreen.V107.Types.MessageStatus -> Evergreen.V109.Types.MessageStatus
migrate_Types_MessageStatus old =
    case old of
        Evergreen.V107.Types.MSWhite ->
            Evergreen.V109.Types.MSWhite

        Evergreen.V107.Types.MSYellow ->
            Evergreen.V109.Types.MSYellow

        Evergreen.V107.Types.MSBlue ->
            Evergreen.V109.Types.MSBlue

        Evergreen.V107.Types.MSRed ->
            Evergreen.V109.Types.MSRed


migrate_Types_PopupState : Evergreen.V107.Types.PopupState -> Evergreen.V109.Types.PopupState
migrate_Types_PopupState old =
    case old of
        Evergreen.V107.Types.NoPopup ->
            Evergreen.V109.Types.NoPopup

        Evergreen.V107.Types.AdminPopup ->
            Evergreen.V109.Types.AdminPopup

        Evergreen.V107.Types.ManualPopup ->
            Evergreen.V109.Types.ManualPopup

        Evergreen.V107.Types.NewDataSetPopup ->
            Evergreen.V109.Types.NewDataSetPopup

        Evergreen.V107.Types.EditDataSetPopup p0 ->
            Evergreen.V109.Types.EditDataSetPopup (p0 |> migrate_Notebook_DataSet_DataSetMetaData)

        Evergreen.V107.Types.SignUpPopup ->
            Evergreen.V109.Types.SignUpPopup

        Evergreen.V107.Types.PackageListPopup ->
            Evergreen.V109.Types.PackageListPopup

        Evergreen.V107.Types.CLIPopup ->
            Evergreen.V109.Types.CLIPopup

        Evergreen.V107.Types.NewNotebookPopup ->
            Evergreen.V109.Types.NewNotebookPopup

        Evergreen.V107.Types.StateEditorPopup ->
            Evergreen.V109.Types.StateEditorPopup

        Evergreen.V107.Types.ViewPublicDataSetsPopup ->
            Evergreen.V109.Types.ViewPublicDataSetsPopup

        Evergreen.V107.Types.ViewPrivateDataSetsPopup ->
            Evergreen.V109.Types.ViewPrivateDataSetsPopup


migrate_Types_ShowNotebooks : Evergreen.V107.Types.ShowNotebooks -> Evergreen.V109.Types.ShowNotebooks
migrate_Types_ShowNotebooks old =
    case old of
        Evergreen.V107.Types.ShowUserNotebooks ->
            Evergreen.V109.Types.ShowUserNotebooks

        Evergreen.V107.Types.ShowPublicNotebooks ->
            Evergreen.V109.Types.ShowPublicNotebooks


migrate_Types_SignupState : Evergreen.V107.Types.SignupState -> Evergreen.V109.Types.SignupState
migrate_Types_SignupState old =
    case old of
        Evergreen.V107.Types.ShowSignUpForm ->
            Evergreen.V109.Types.ShowSignUpForm

        Evergreen.V107.Types.HideSignUpForm ->
            Evergreen.V109.Types.HideSignUpForm


migrate_Types_ToBackend : Evergreen.V107.Types.ToBackend -> Evergreen.V109.Types.ToBackend
migrate_Types_ToBackend old =
    case old of
        Evergreen.V107.Types.NoOpToBackend ->
            Evergreen.V109.Types.NoOpToBackend

        Evergreen.V107.Types.GetRandomSeed ->
            Evergreen.V109.Types.GetRandomSeed

        Evergreen.V107.Types.RunTask ->
            Evergreen.V109.Types.RunTask

        Evergreen.V107.Types.SendUsers ->
            Evergreen.V109.Types.SendUsers

        Evergreen.V107.Types.DeleteDataSet p0 ->
            Evergreen.V109.Types.DeleteDataSet (p0 |> migrate_Notebook_DataSet_DataSetMetaData)

        Evergreen.V107.Types.SaveDataSet p0 ->
            Evergreen.V109.Types.SaveDataSet (p0 |> migrate_Notebook_DataSet_DataSetMetaData)

        Evergreen.V107.Types.GetListOfDataSets p0 ->
            Evergreen.V109.Types.GetListOfDataSets (p0 |> migrate_Types_DataSetDescription)

        Evergreen.V107.Types.CreateDataSet p0 ->
            Evergreen.V109.Types.CreateDataSet (p0 |> migrate_Notebook_DataSet_DataSet)

        Evergreen.V107.Types.GetData p0 p1 p2 ->
            Evergreen.V109.Types.GetData p0 p1 p2

        Evergreen.V107.Types.GetDataSetForDownload p0 ->
            Evergreen.V109.Types.GetDataSetForDownload p0

        Evergreen.V107.Types.SaveElmJsonDependenciesBE p0 p1 ->
            Evergreen.V109.Types.SaveElmJsonDependenciesBE p0 p1

        Evergreen.V107.Types.CreateNotebook p0 p1 ->
            Evergreen.V109.Types.CreateNotebook p0 p1

        Evergreen.V107.Types.ImportNewBook p0 p1 ->
            Evergreen.V109.Types.ImportNewBook p0 (p1 |> migrate_Notebook_Book_Book)

        Evergreen.V107.Types.SaveNotebook p0 ->
            Evergreen.V109.Types.SaveNotebook (p0 |> migrate_Notebook_Book_Book)

        Evergreen.V107.Types.DeleteNotebook p0 ->
            Evergreen.V109.Types.DeleteNotebook (p0 |> migrate_Notebook_Book_Book)

        Evergreen.V107.Types.GetPublicNotebook p0 ->
            Evergreen.V109.Types.GetPublicNotebook p0

        Evergreen.V107.Types.GetClonedNotebook p0 p1 ->
            Evergreen.V109.Types.GetClonedNotebook p0 p1

        Evergreen.V107.Types.GetPulledNotebook p0 p1 p2 p3 ->
            Evergreen.V109.Types.GetPulledNotebook p0 p1 p2 p3

        Evergreen.V107.Types.UpdateSlugDict p0 ->
            Evergreen.V109.Types.UpdateSlugDict (p0 |> migrate_Notebook_Book_Book)

        Evergreen.V107.Types.GetUsersNotebooks p0 ->
            Evergreen.V109.Types.GetUsersNotebooks p0

        Evergreen.V107.Types.GetPublicNotebooks p0 p1 ->
            Evergreen.V109.Types.GetPublicNotebooks (p0 |> Maybe.map migrate_Notebook_Book_Book) p1

        Evergreen.V107.Types.SignUpBE p0 p1 p2 ->
            Evergreen.V109.Types.SignUpBE p0 p1 p2

        Evergreen.V107.Types.SignInBEDev ->
            Evergreen.V109.Types.SignInBEDev

        Evergreen.V107.Types.SignInBE p0 p1 ->
            Evergreen.V109.Types.SignInBE p0 p1

        Evergreen.V107.Types.SignOutBE p0 ->
            Evergreen.V109.Types.SignOutBE p0

        Evergreen.V107.Types.UpdateUserWith p0 ->
            Evergreen.V109.Types.UpdateUserWith (p0 |> migrate_User_User)


migrate_Types_ToFrontend : Evergreen.V107.Types.ToFrontend -> Evergreen.V109.Types.ToFrontend
migrate_Types_ToFrontend old =
    case old of
        Evergreen.V107.Types.NoOpToFrontend ->
            Evergreen.V109.Types.NoOpToFrontend

        Evergreen.V107.Types.MessageReceived p0 ->
            Evergreen.V109.Types.MessageReceived (p0 |> migrate_Types_Message)

        Evergreen.V107.Types.GotRandomSeed p0 ->
            Evergreen.V109.Types.GotRandomSeed p0

        Evergreen.V107.Types.GotUsers p0 ->
            Evergreen.V109.Types.GotUsers p0

        Evergreen.V107.Types.GotListOfPublicDataSets p0 ->
            Evergreen.V109.Types.GotListOfPublicDataSets p0

        Evergreen.V107.Types.GotListOfPrivateDataSets p0 ->
            Evergreen.V109.Types.GotListOfPrivateDataSets p0

        Evergreen.V107.Types.GotData p0 p1 p2 ->
            Evergreen.V109.Types.GotData p0 p1 (p2 |> migrate_Notebook_DataSet_DataSet)

        Evergreen.V107.Types.GotDataForDownload p0 ->
            Evergreen.V109.Types.GotDataForDownload (p0 |> migrate_Notebook_DataSet_DataSet)

        Evergreen.V107.Types.GotPackageDict p0 ->
            Evergreen.V109.Types.GotPackageDict p0

        Evergreen.V107.Types.GotNotebook p0 ->
            Evergreen.V109.Types.GotNotebook (p0 |> migrate_Notebook_Book_Book)

        Evergreen.V107.Types.GotPublicNotebook p0 ->
            Evergreen.V109.Types.GotPublicNotebook (p0 |> migrate_Notebook_Book_Book)

        Evergreen.V107.Types.GotNotebooks p0 p1 ->
            Evergreen.V109.Types.GotNotebooks (p0 |> Maybe.map migrate_Notebook_Book_Book)
                (p1 |> List.map migrate_Notebook_Book_Book)

        Evergreen.V107.Types.SendMessage p0 ->
            Evergreen.V109.Types.SendMessage p0

        Evergreen.V107.Types.UserSignedIn p0 p1 ->
            Evergreen.V109.Types.UserSignedIn (p0 |> migrate_User_User) p1

        Evergreen.V107.Types.SendUser p0 ->
            Evergreen.V109.Types.SendUser (p0 |> migrate_User_User)


migrate_User_User : Evergreen.V107.User.User -> Evergreen.V109.User.User
migrate_User_User old =
    old
