module Evergreen.Migrate.V114 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Evergreen.V113.Notebook.Book
import Evergreen.V113.Notebook.Cell
import Evergreen.V113.Notebook.DataSet
import Evergreen.V113.Notebook.Types
import Evergreen.V113.Types
import Evergreen.V113.User
import Evergreen.V114.Notebook.Book
import Evergreen.V114.Notebook.Cell
import Evergreen.V114.Notebook.DataSet
import Evergreen.V114.Notebook.Types
import Evergreen.V114.Types
import Evergreen.V114.User
import Lamdera.Migrations exposing (..)
import List
import Maybe


frontendModel : Evergreen.V113.Types.FrontendModel -> ModelMigration Evergreen.V114.Types.FrontendModel Evergreen.V114.Types.FrontendMsg
frontendModel old =
    ModelUnchanged


backendModel : Evergreen.V113.Types.BackendModel -> ModelMigration Evergreen.V114.Types.BackendModel Evergreen.V114.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V113.Types.FrontendMsg -> MsgMigration Evergreen.V114.Types.FrontendMsg Evergreen.V114.Types.FrontendMsg
frontendMsg old =
    MsgUnchanged


toBackend : Evergreen.V113.Types.ToBackend -> MsgMigration Evergreen.V114.Types.ToBackend Evergreen.V114.Types.BackendMsg
toBackend old =
    MsgMigrated ( migrate_Types_ToBackend old, Cmd.none )


backendMsg : Evergreen.V113.Types.BackendMsg -> MsgMigration Evergreen.V114.Types.BackendMsg Evergreen.V114.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V113.Types.ToFrontend -> MsgMigration Evergreen.V114.Types.ToFrontend Evergreen.V114.Types.FrontendMsg
toFrontend old =
    MsgUnchanged


migrate_Notebook_Book_Book : Evergreen.V113.Notebook.Book.Book -> Evergreen.V114.Notebook.Book.Book
migrate_Notebook_Book_Book old =
    { id = old.id
    , dirty = old.dirty
    , slug = old.slug
    , origin = old.origin
    , author = old.author
    , createdAt = old.createdAt
    , updatedAt = old.updatedAt
    , public = old.public
    , title = old.title
    , cells = old.cells |> List.map migrate_Notebook_Cell_Cell
    , currentIndex = old.currentIndex
    , packageNames = old.packageNames
    , tags = old.tags
    , options = old.options
    }


migrate_Notebook_Cell_Cell : Evergreen.V113.Notebook.Cell.Cell -> Evergreen.V114.Notebook.Cell.Cell
migrate_Notebook_Cell_Cell old =
    { index = old.index
    , text = old.text
    , tipe = old.tipe |> migrate_Notebook_Cell_CellType
    , value = old.value |> migrate_Notebook_Cell_CellValue
    , cellState = old.cellState |> migrate_Notebook_Cell_CellState
    , commented = old.commented
    , locked = old.locked
    , report = old.report |> Tuple.mapSecond (Maybe.map (List.map migrate_Notebook_Types_MessageItem))
    , replData = old.replData
    }


migrate_Notebook_Cell_CellState : Evergreen.V113.Notebook.Cell.CellState -> Evergreen.V114.Notebook.Cell.CellState
migrate_Notebook_Cell_CellState old =
    case old of
        Evergreen.V113.Notebook.Cell.CSEdit ->
            Evergreen.V114.Notebook.Cell.CSEdit

        Evergreen.V113.Notebook.Cell.CSView ->
            Evergreen.V114.Notebook.Cell.CSView


migrate_Notebook_Cell_CellType : Evergreen.V113.Notebook.Cell.CellType -> Evergreen.V114.Notebook.Cell.CellType
migrate_Notebook_Cell_CellType old =
    case old of
        Evergreen.V113.Notebook.Cell.CTCode ->
            Evergreen.V114.Notebook.Cell.CTCode

        Evergreen.V113.Notebook.Cell.CTMarkdown ->
            Evergreen.V114.Notebook.Cell.CTMarkdown


migrate_Notebook_Cell_CellValue : Evergreen.V113.Notebook.Cell.CellValue -> Evergreen.V114.Notebook.Cell.CellValue
migrate_Notebook_Cell_CellValue old =
    case old of
        Evergreen.V113.Notebook.Cell.CVString p0 ->
            Evergreen.V114.Notebook.Cell.CVString p0

        Evergreen.V113.Notebook.Cell.CVMarkdown p0 ->
            Evergreen.V114.Notebook.Cell.CVMarkdown p0

        Evergreen.V113.Notebook.Cell.CVNone ->
            Evergreen.V114.Notebook.Cell.CVNone


migrate_Notebook_DataSet_DataSet : Evergreen.V113.Notebook.DataSet.DataSet -> Evergreen.V114.Notebook.DataSet.DataSet
migrate_Notebook_DataSet_DataSet old =
    old


migrate_Notebook_DataSet_DataSetMetaData : Evergreen.V113.Notebook.DataSet.DataSetMetaData -> Evergreen.V114.Notebook.DataSet.DataSetMetaData
migrate_Notebook_DataSet_DataSetMetaData old =
    old


migrate_Notebook_Types_MessageItem : Evergreen.V113.Notebook.Types.MessageItem -> Evergreen.V114.Notebook.Types.MessageItem
migrate_Notebook_Types_MessageItem old =
    case old of
        Evergreen.V113.Notebook.Types.Plain p0 ->
            Evergreen.V114.Notebook.Types.Plain p0

        Evergreen.V113.Notebook.Types.Styled p0 ->
            Evergreen.V114.Notebook.Types.Styled (p0 |> migrate_Notebook_Types_StyledString)


migrate_Notebook_Types_StyledString : Evergreen.V113.Notebook.Types.StyledString -> Evergreen.V114.Notebook.Types.StyledString
migrate_Notebook_Types_StyledString old =
    old


migrate_Types_DataSetDescription : Evergreen.V113.Types.DataSetDescription -> Evergreen.V114.Types.DataSetDescription
migrate_Types_DataSetDescription old =
    case old of
        Evergreen.V113.Types.PublicDatasets ->
            Evergreen.V114.Types.PublicDatasets

        Evergreen.V113.Types.UserDatasets p0 ->
            Evergreen.V114.Types.UserDatasets p0


migrate_Types_ToBackend : Evergreen.V113.Types.ToBackend -> Evergreen.V114.Types.ToBackend
migrate_Types_ToBackend old =
    case old of
        Evergreen.V113.Types.NoOpToBackend ->
            Evergreen.V114.Types.NoOpToBackend

        Evergreen.V113.Types.GetRandomSeed ->
            Evergreen.V114.Types.GetRandomSeed

        Evergreen.V113.Types.RunTask ->
            Evergreen.V114.Types.RunTask

        Evergreen.V113.Types.SendUsers ->
            Evergreen.V114.Types.SendUsers

        Evergreen.V113.Types.DeleteDataSet p0 ->
            Evergreen.V114.Types.DeleteDataSet (p0 |> migrate_Notebook_DataSet_DataSetMetaData)

        Evergreen.V113.Types.SaveDataSet p0 ->
            Evergreen.V114.Types.SaveDataSet (p0 |> migrate_Notebook_DataSet_DataSetMetaData)

        Evergreen.V113.Types.GetListOfDataSets p0 ->
            Evergreen.V114.Types.GetListOfDataSets (p0 |> migrate_Types_DataSetDescription)

        Evergreen.V113.Types.CreateDataSet p0 ->
            Evergreen.V114.Types.CreateDataSet (p0 |> migrate_Notebook_DataSet_DataSet)

        Evergreen.V113.Types.GetData p0 p1 p2 ->
            Evergreen.V114.Types.GetData p0 p1 p2

        Evergreen.V113.Types.GetDataSetForDownload p0 ->
            Evergreen.V114.Types.GetDataSetForDownload p0

        Evergreen.V113.Types.GetCellsToInclude p0 ->
            Evergreen.V114.Types.GetCellsToInclude p0

        Evergreen.V113.Types.SaveElmJsonDependenciesBE p0 p1 ->
            Evergreen.V114.Types.SaveElmJsonDependenciesBE p0 p1

        Evergreen.V113.Types.CreateNotebook p0 p1 ->
            Evergreen.V114.Types.CreateNotebook p0 p1

        Evergreen.V113.Types.ImportNewBook p0 p1 ->
            Evergreen.V114.Types.ImportNewBook p0 (p1 |> migrate_Notebook_Book_Book)

        Evergreen.V113.Types.SaveNotebook p0 ->
            Evergreen.V114.Types.SaveNotebook (p0 |> migrate_Notebook_Book_Book)

        Evergreen.V113.Types.DeleteNotebook p0 ->
            Evergreen.V114.Types.DeleteNotebook (p0 |> migrate_Notebook_Book_Book)

        Evergreen.V113.Types.GetPublicNotebook p0 ->
            Evergreen.V114.Types.GetPublicNotebook p0

        Evergreen.V113.Types.GetClonedNotebook p0 p1 ->
            Evergreen.V114.Types.GetClonedNotebook p0
                p1
                "foo"

        Evergreen.V113.Types.GetPulledNotebook p0 p1 p2 p3 ->
            Evergreen.V114.Types.GetPulledNotebook p0 p1 p2 p3

        Evergreen.V113.Types.UpdateSlugDict p0 ->
            Evergreen.V114.Types.UpdateSlugDict (p0 |> migrate_Notebook_Book_Book)

        Evergreen.V113.Types.GetUsersNotebooks p0 ->
            Evergreen.V114.Types.GetUsersNotebooks p0

        Evergreen.V113.Types.GetPublicNotebooks p0 p1 ->
            Evergreen.V114.Types.GetPublicNotebooks (p0 |> Maybe.map migrate_Notebook_Book_Book) p1

        Evergreen.V113.Types.SignUpBE p0 p1 p2 ->
            Evergreen.V114.Types.SignUpBE p0 p1 p2

        Evergreen.V113.Types.SignInBEDev ->
            Evergreen.V114.Types.SignInBEDev

        Evergreen.V113.Types.SignInBE p0 p1 ->
            Evergreen.V114.Types.SignInBE p0 p1

        Evergreen.V113.Types.SignOutBE p0 ->
            Evergreen.V114.Types.SignOutBE p0

        Evergreen.V113.Types.UpdateUserWith p0 ->
            Evergreen.V114.Types.UpdateUserWith (p0 |> migrate_User_User)


migrate_User_User : Evergreen.V113.User.User -> Evergreen.V114.User.User
migrate_User_User old =
    old
