module Evergreen.Migrate.V131 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Dict
import Evergreen.V114.Authentication
import Evergreen.V114.Credentials
import Evergreen.V114.Notebook.Book
import Evergreen.V114.Notebook.Cell
import Evergreen.V114.Notebook.DataSet
import Evergreen.V114.Notebook.Types
import Evergreen.V114.Types
import Evergreen.V114.User
import Evergreen.V131.Authentication
import Evergreen.V131.Credentials
import Evergreen.V131.Notebook.Book
import Evergreen.V131.Notebook.Cell
import Evergreen.V131.Notebook.DataSet
import Evergreen.V131.Notebook.Types
import Evergreen.V131.Types
import Evergreen.V131.User
import Lamdera.Migrations exposing (..)
import List
import Maybe


frontendModel : Evergreen.V114.Types.FrontendModel -> ModelMigration Evergreen.V131.Types.FrontendModel Evergreen.V131.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V114.Types.BackendModel -> ModelMigration Evergreen.V131.Types.BackendModel Evergreen.V131.Types.BackendMsg
backendModel old =
    ModelMigrated ( migrate_Types_BackendModel old, Cmd.none )


frontendMsg : Evergreen.V114.Types.FrontendMsg -> MsgMigration Evergreen.V131.Types.FrontendMsg Evergreen.V131.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V114.Types.ToBackend -> MsgMigration Evergreen.V131.Types.ToBackend Evergreen.V131.Types.BackendMsg
toBackend old =
    MsgMigrated ( migrate_Types_ToBackend old, Cmd.none )


backendMsg : Evergreen.V114.Types.BackendMsg -> MsgMigration Evergreen.V131.Types.BackendMsg Evergreen.V131.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V114.Types.ToFrontend -> MsgMigration Evergreen.V131.Types.ToFrontend Evergreen.V131.Types.FrontendMsg
toFrontend old =
    MsgMigrated ( migrate_Types_ToFrontend old, Cmd.none )


migrate_Types_BackendModel : Evergreen.V114.Types.BackendModel -> Evergreen.V131.Types.BackendModel
migrate_Types_BackendModel old =
    { currentTime = old.currentTime
    , randomSeed = old.randomSeed
    , uuidCount = old.uuidCount
    , uuid = old.uuid
    , randomAtmosphericInt = old.randomAtmosphericInt
    , dataSetLibrary = old.dataSetLibrary
    , userToNoteBookDict = old.userToNoteBookDict |> migrate_Types_UserToNotebookDict
    , usernameToPackageDictDict = old.usernameToPackageDictDict
    , slugDict = old.slugDict
    , authenticationDict = old.authenticationDict |> migrate_Authentication_AuthenticationDict
    }


migrate_Types_FrontendModel : Evergreen.V114.Types.FrontendModel -> Evergreen.V131.Types.FrontendModel
migrate_Types_FrontendModel old =
    { key = old.key
    , url = old.url
    , messages = old.messages |> List.map migrate_Types_Message
    , appState = old.appState |> migrate_Types_AppState
    , appMode = old.appMode |> migrate_Types_AppMode
    , currentTime = old.currentTime
    , tickCount = old.tickCount
    , clockState = old.clockState |> migrate_Types_ClockState
    , pressedKeys = old.pressedKeys
    , randomSeed = old.randomSeed
    , randomProbabilities = old.randomProbabilities
    , probabilityVectorLength = old.probabilityVectorLength
    , messageId = old.messageId
    , users = old.users
    , inputName = old.inputName
    , inputIdentifier = old.inputIdentifier
    , inputAuthor = old.inputAuthor
    , inputDescription = old.inputDescription
    , inputComments = old.inputComments
    , inputData = old.inputData
    , inputCommand = old.inputCommand
    , inputPackages = old.inputPackages
    , inputInitialStateValue = old.inputInitialStateValue
    , publicDataSetMetaDataList = old.publicDataSetMetaDataList
    , privateDataSetMetaDataList = old.privateDataSetMetaDataList
    , includedCells = old.includedCells |> List.map migrate_Notebook_Cell_Cell
    , errorReports = old.errorReports |> List.map migrate_Notebook_Types_ErrorReport
    , showErrorPanel = old.showErrorPanel
    , theme = old.theme |> migrate_Notebook_Book_Theme
    , evalState = old.evalState |> migrate_Notebook_Types_EvalState
    , packagesFromCompiler = old.packagesFromCompiler
    , packageDict = old.packageDict
    , elmJsonError = old.elmJsonError
    , kvDict = old.kvDict
    , books = old.books |> List.map migrate_Notebook_Book_Book
    , currentCell = old.currentCell |> Maybe.map migrate_Notebook_Cell_Cell
    , cellInsertionDirection = old.cellInsertionDirection |> migrate_Notebook_Types_CellDirection
    , currentBook = old.currentBook |> migrate_Notebook_Book_Book
    , cellContent = old.cellContent
    , currentCellIndex = old.currentCellIndex
    , cloneReference = old.cloneReference
    , deleteNotebookState = old.deleteNotebookState |> migrate_Types_DeleteNotebookState
    , showNotebooks = old.showNotebooks |> migrate_Types_ShowNotebooks
    , signupState = old.signupState |> migrate_Types_SignupState
    , currentUser = old.currentUser
    , inputUsername = old.inputUsername
    , inputSignupUsername = old.inputSignupUsername
    , inputEmail = old.inputEmail
    , inputRealname = old.inputRealname
    , inputPassword = old.inputPassword
    , inputPasswordAgain = old.inputPasswordAgain
    , inputTitle = old.inputTitle
    , windowWidth = old.windowWidth
    , windowHeight = old.windowHeight
    , popupState = old.popupState |> migrate_Types_PopupState
    , showEditor = old.showEditor
    }


migrate_Authentication_AuthenticationDict : Evergreen.V114.Authentication.AuthenticationDict -> Evergreen.V131.Authentication.AuthenticationDict
migrate_Authentication_AuthenticationDict old =
    old |> Dict.map (\k -> migrate_Authentication_UserData)


migrate_Authentication_UserData : Evergreen.V114.Authentication.UserData -> Evergreen.V131.Authentication.UserData
migrate_Authentication_UserData old =
    { user = old.user |> migrate_User_User
    , credentials = old.credentials |> migrate_Credentials_Credentials
    }


migrate_Credentials_Credentials : Evergreen.V114.Credentials.Credentials -> Evergreen.V131.Credentials.Credentials
migrate_Credentials_Credentials old =
    case old of
        Evergreen.V114.Credentials.V1 p0 p1 ->
            Evergreen.V131.Credentials.V1 p0 p1


migrate_Notebook_Book_Book : Evergreen.V114.Notebook.Book.Book -> Evergreen.V131.Notebook.Book.Book
migrate_Notebook_Book_Book old =
    { id = old.id
    , dirty = old.dirty
    , slug = old.slug
    , origin = old.origin
    , author = old.author
    , createdAt = old.createdAt
    , updatedAt = old.updatedAt
    , public = old.public
    , title = old.title
    , cells = old.cells |> List.map migrate_Notebook_Cell_Cell
    , currentIndex = old.currentIndex
    , packageNames = old.packageNames
    , tags = old.tags
    , options = old.options
    }


migrate_Notebook_Book_DirectionToMove : Evergreen.V114.Notebook.Book.DirectionToMove -> Evergreen.V131.Notebook.Book.DirectionToMove
migrate_Notebook_Book_DirectionToMove old =
    case old of
        Evergreen.V114.Notebook.Book.Up ->
            Evergreen.V131.Notebook.Book.Up

        Evergreen.V114.Notebook.Book.Down ->
            Evergreen.V131.Notebook.Book.Down


migrate_Notebook_Book_Theme : Evergreen.V114.Notebook.Book.Theme -> Evergreen.V131.Notebook.Book.Theme
migrate_Notebook_Book_Theme old =
    case old of
        Evergreen.V114.Notebook.Book.DarkTheme ->
            Evergreen.V131.Notebook.Book.DarkTheme

        Evergreen.V114.Notebook.Book.LightTheme ->
            Evergreen.V131.Notebook.Book.LightTheme


migrate_Notebook_Cell_Cell : Evergreen.V114.Notebook.Cell.Cell -> Evergreen.V131.Notebook.Cell.Cell
migrate_Notebook_Cell_Cell old =
    { index = old.index
    , text = old.text
    , tipe = old.tipe |> migrate_Notebook_Cell_CellType
    , value = old.value |> migrate_Notebook_Cell_CellValue
    , cellState = old.cellState |> migrate_Notebook_Cell_CellState
    , commented = old.commented
    , locked = old.locked
    , report = old.report |> Tuple.mapSecond (Maybe.map (List.map migrate_Notebook_Types_MessageItem))
    , replData = old.replData
    , highlightTime = 0
    }


migrate_Notebook_Cell_CellState : Evergreen.V114.Notebook.Cell.CellState -> Evergreen.V131.Notebook.Cell.CellState
migrate_Notebook_Cell_CellState old =
    case old of
        Evergreen.V114.Notebook.Cell.CSEdit ->
            Evergreen.V131.Notebook.Cell.CSEdit

        Evergreen.V114.Notebook.Cell.CSView ->
            Evergreen.V131.Notebook.Cell.CSView


migrate_Notebook_Cell_CellType : Evergreen.V114.Notebook.Cell.CellType -> Evergreen.V131.Notebook.Cell.CellType
migrate_Notebook_Cell_CellType old =
    case old of
        Evergreen.V114.Notebook.Cell.CTCode ->
            Evergreen.V131.Notebook.Cell.CTCode

        Evergreen.V114.Notebook.Cell.CTMarkdown ->
            Evergreen.V131.Notebook.Cell.CTMarkdown


migrate_Notebook_Cell_CellValue : Evergreen.V114.Notebook.Cell.CellValue -> Evergreen.V131.Notebook.Cell.CellValue
migrate_Notebook_Cell_CellValue old =
    case old of
        Evergreen.V114.Notebook.Cell.CVString p0 ->
            Evergreen.V131.Notebook.Cell.CVString p0

        Evergreen.V114.Notebook.Cell.CVMarkdown p0 ->
            Evergreen.V131.Notebook.Cell.CVMarkdown p0

        Evergreen.V114.Notebook.Cell.CVNone ->
            Evergreen.V131.Notebook.Cell.CVNone


migrate_Notebook_DataSet_DataSet : Evergreen.V114.Notebook.DataSet.DataSet -> Evergreen.V131.Notebook.DataSet.DataSet
migrate_Notebook_DataSet_DataSet old =
    old


migrate_Notebook_DataSet_DataSetMetaData : Evergreen.V114.Notebook.DataSet.DataSetMetaData -> Evergreen.V131.Notebook.DataSet.DataSetMetaData
migrate_Notebook_DataSet_DataSetMetaData old =
    old


migrate_Notebook_Types_CellDirection : Evergreen.V114.Notebook.Types.CellDirection -> Evergreen.V131.Notebook.Types.CellDirection
migrate_Notebook_Types_CellDirection old =
    case old of
        Evergreen.V114.Notebook.Types.Up ->
            Evergreen.V131.Notebook.Types.Up

        Evergreen.V114.Notebook.Types.Down ->
            Evergreen.V131.Notebook.Types.Down


migrate_Notebook_Types_ErrorReport : Evergreen.V114.Notebook.Types.ErrorReport -> Evergreen.V131.Notebook.Types.ErrorReport
migrate_Notebook_Types_ErrorReport old =
    old |> Tuple.mapSecond (List.map migrate_Notebook_Types_MessageItem)


migrate_Notebook_Types_EvalState : Evergreen.V114.Notebook.Types.EvalState -> Evergreen.V131.Notebook.Types.EvalState
migrate_Notebook_Types_EvalState old =
    old


migrate_Notebook_Types_MessageItem : Evergreen.V114.Notebook.Types.MessageItem -> Evergreen.V131.Notebook.Types.MessageItem
migrate_Notebook_Types_MessageItem old =
    case old of
        Evergreen.V114.Notebook.Types.Plain p0 ->
            Evergreen.V131.Notebook.Types.Plain p0

        Evergreen.V114.Notebook.Types.Styled p0 ->
            Evergreen.V131.Notebook.Types.Styled (p0 |> migrate_Notebook_Types_StyledString)


migrate_Notebook_Types_StyledString : Evergreen.V114.Notebook.Types.StyledString -> Evergreen.V131.Notebook.Types.StyledString
migrate_Notebook_Types_StyledString old =
    old


migrate_Types_AppMode : Evergreen.V114.Types.AppMode -> Evergreen.V131.Types.AppMode
migrate_Types_AppMode old =
    case old of
        Evergreen.V114.Types.AMWorking ->
            Evergreen.V131.Types.AMWorking

        Evergreen.V114.Types.AMEditTitle ->
            Evergreen.V131.Types.AMEditTitle


migrate_Types_AppState : Evergreen.V114.Types.AppState -> Evergreen.V131.Types.AppState
migrate_Types_AppState old =
    case old of
        Evergreen.V114.Types.Loading ->
            Evergreen.V131.Types.Loading

        Evergreen.V114.Types.Loaded ->
            Evergreen.V131.Types.Loaded


migrate_Types_ClockState : Evergreen.V114.Types.ClockState -> Evergreen.V131.Types.ClockState
migrate_Types_ClockState old =
    case old of
        Evergreen.V114.Types.ClockRunning ->
            Evergreen.V131.Types.ClockRunning

        Evergreen.V114.Types.ClockStopped ->
            Evergreen.V131.Types.ClockStopped

        Evergreen.V114.Types.ClockPaused ->
            Evergreen.V131.Types.ClockPaused


migrate_Types_DataSetDescription : Evergreen.V114.Types.DataSetDescription -> Evergreen.V131.Types.DataSetDescription
migrate_Types_DataSetDescription old =
    case old of
        Evergreen.V114.Types.PublicDatasets ->
            Evergreen.V131.Types.PublicDatasets

        Evergreen.V114.Types.UserDatasets p0 ->
            Evergreen.V131.Types.UserDatasets p0


migrate_Types_DeleteNotebookState : Evergreen.V114.Types.DeleteNotebookState -> Evergreen.V131.Types.DeleteNotebookState
migrate_Types_DeleteNotebookState old =
    case old of
        Evergreen.V114.Types.WaitingToDeleteNotebook ->
            Evergreen.V131.Types.WaitingToDeleteNotebook

        Evergreen.V114.Types.CanDeleteNotebook ->
            Evergreen.V131.Types.CanDeleteNotebook


migrate_Types_FrontendMsg : Evergreen.V114.Types.FrontendMsg -> Evergreen.V131.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    case old of
        Evergreen.V114.Types.UrlClicked p0 ->
            Evergreen.V131.Types.UrlClicked p0

        Evergreen.V114.Types.UrlChanged p0 ->
            Evergreen.V131.Types.UrlChanged p0

        Evergreen.V114.Types.NoOpFrontendMsg ->
            Evergreen.V131.Types.NoOpFrontendMsg

        Evergreen.V114.Types.FETick p0 ->
            Evergreen.V131.Types.FETick p0

        Evergreen.V114.Types.KeyboardMsg p0 ->
            Evergreen.V131.Types.KeyboardMsg p0

        Evergreen.V114.Types.GetRandomProbabilities p0 ->
            Evergreen.V131.Types.GetRandomProbabilities p0

        Evergreen.V114.Types.GotRandomProbabilities p0 ->
            Evergreen.V131.Types.GotRandomProbabilities p0

        Evergreen.V114.Types.StringDataRequested p0 p1 ->
            Evergreen.V131.Types.StringDataRequested p0 p1

        Evergreen.V114.Types.StringDataSelected p0 p1 p2 ->
            Evergreen.V131.Types.StringDataSelected p0 p1 p2

        Evergreen.V114.Types.StringDataLoaded p0 p1 p2 p3 ->
            Evergreen.V131.Types.StringDataLoaded p0 p1 p2 p3

        Evergreen.V114.Types.InputName p0 ->
            Evergreen.V131.Types.InputName p0

        Evergreen.V114.Types.InputIdentifier p0 ->
            Evergreen.V131.Types.InputIdentifier p0

        Evergreen.V114.Types.InputDescription p0 ->
            Evergreen.V131.Types.InputDescription p0

        Evergreen.V114.Types.InputComments p0 ->
            Evergreen.V131.Types.InputComments p0

        Evergreen.V114.Types.InputData p0 ->
            Evergreen.V131.Types.InputData p0

        Evergreen.V114.Types.InputCommand p0 ->
            Evergreen.V131.Types.InputCommand p0

        Evergreen.V114.Types.InputPackages p0 ->
            Evergreen.V131.Types.InputPackages p0

        Evergreen.V114.Types.InputAuthor p0 ->
            Evergreen.V131.Types.InputAuthor p0

        Evergreen.V114.Types.InputInitialStateValue p0 ->
            Evergreen.V131.Types.InputInitialStateValue p0

        Evergreen.V114.Types.SendProgramToBeCompiled ->
            Evergreen.V131.Types.SendProgramToBeCompiled

        Evergreen.V114.Types.GotCompiledProgram p0 ->
            Evergreen.V131.Types.GotCompiledProgram p0

        Evergreen.V114.Types.ToggleTheme p0 ->
            Evergreen.V131.Types.ToggleTheme (p0 |> migrate_Notebook_Book_Theme)

        Evergreen.V114.Types.ExecuteDelayedFunction ->
            Evergreen.V131.Types.ExecuteDelayedFunction

        Evergreen.V114.Types.ExecuteDelayedFunction2 ->
            Evergreen.V131.Types.ExecuteDelayedFunction2

        Evergreen.V114.Types.ExecuteDelayedMessageRemoval p0 ->
            Evergreen.V131.Types.ExecuteDelayedMessageRemoval p0

        Evergreen.V114.Types.GetPackagesFromCompiler ->
            Evergreen.V131.Types.GetPackagesFromCompiler

        Evergreen.V114.Types.GotPackagesFromCompiler p0 ->
            Evergreen.V131.Types.GotPackagesFromCompiler p0

        Evergreen.V114.Types.GotElmJsonDict p0 ->
            Evergreen.V131.Types.GotElmJsonDict p0

        Evergreen.V114.Types.GotReplyFromCompiler p0 p1 ->
            Evergreen.V131.Types.GotReplyFromCompiler (p0 |> migrate_Notebook_Cell_Cell) p1

        Evergreen.V114.Types.ReceivedFromJS p0 ->
            Evergreen.V131.Types.ReceivedFromJS p0

        Evergreen.V114.Types.ReceiveJSData p0 ->
            Evergreen.V131.Types.ReceiveJSData p0

        Evergreen.V114.Types.AskToListDataSets p0 ->
            Evergreen.V131.Types.AskToListDataSets (p0 |> migrate_Types_DataSetDescription)

        Evergreen.V114.Types.AskToSaveDataSet p0 ->
            Evergreen.V131.Types.AskToSaveDataSet (p0 |> migrate_Notebook_DataSet_DataSetMetaData)

        Evergreen.V114.Types.AskToCreateDataSet ->
            Evergreen.V131.Types.AskToCreateDataSet

        Evergreen.V114.Types.AskToDeleteDataSet p0 ->
            Evergreen.V131.Types.AskToDeleteDataSet (p0 |> migrate_Notebook_DataSet_DataSetMetaData)

        Evergreen.V114.Types.SubmitPackageList ->
            Evergreen.V131.Types.SubmitPackageList

        Evergreen.V114.Types.SubmitTest ->
            Evergreen.V131.Types.SubmitTest

        Evergreen.V114.Types.RunCommand ->
            Evergreen.V131.Types.RunCommand

        Evergreen.V114.Types.PackageListSent p0 ->
            Evergreen.V131.Types.PackageListSent p0

        Evergreen.V114.Types.ClearNotebookValues ->
            Evergreen.V131.Types.ClearNotebookValues

        Evergreen.V114.Types.ExecuteNotebook ->
            Evergreen.V131.Types.ExecuteNotebook

        Evergreen.V114.Types.UpdateDeclarationsDictionary ->
            Evergreen.V131.Types.UpdateDeclarationsDictionary

        Evergreen.V114.Types.ExecuteCell p0 ->
            Evergreen.V131.Types.ExecuteCell p0

        Evergreen.V114.Types.ExecuteCells p0 ->
            Evergreen.V131.Types.ExecuteCells p0

        Evergreen.V114.Types.UpdateErrorReports ->
            Evergreen.V131.Types.UpdateErrorReports

        Evergreen.V114.Types.FetchDependencies p0 ->
            Evergreen.V131.Types.FetchDependencies p0

        Evergreen.V114.Types.ToggleCellLock p0 ->
            Evergreen.V131.Types.ToggleCellLock (p0 |> migrate_Notebook_Cell_Cell)

        Evergreen.V114.Types.ChangeCellInsertionDirection p0 ->
            Evergreen.V131.Types.ChangeCellInsertionDirection (p0 |> migrate_Notebook_Types_CellDirection)

        Evergreen.V114.Types.NewCodeCell p0 p1 ->
            Evergreen.V131.Types.NewCodeCell (p0 |> migrate_Notebook_Cell_CellState) p1

        Evergreen.V114.Types.NewMarkdownCell p0 p1 ->
            Evergreen.V131.Types.NewMarkdownCell (p0 |> migrate_Notebook_Cell_CellState) p1

        Evergreen.V114.Types.ToggleShowErrorPanel ->
            Evergreen.V131.Types.ToggleShowErrorPanel

        Evergreen.V114.Types.DeleteCell p0 ->
            Evergreen.V131.Types.DeleteCell p0

        Evergreen.V114.Types.MoveCell p0 p1 ->
            Evergreen.V131.Types.MoveCell p0 (p1 |> migrate_Notebook_Book_DirectionToMove)

        Evergreen.V114.Types.ToggleComment p0 p1 ->
            Evergreen.V131.Types.ToggleComment p0 p1

        Evergreen.V114.Types.EditCell p0 ->
            Evergreen.V131.Types.EditCell (p0 |> migrate_Notebook_Cell_Cell)

        Evergreen.V114.Types.ClearCell p0 ->
            Evergreen.V131.Types.ClearCell p0

        Evergreen.V114.Types.EvalCell p0 ->
            Evergreen.V131.Types.EvalCell (p0 |> migrate_Notebook_Cell_CellState)

        Evergreen.V114.Types.InputElmCode p0 p1 ->
            Evergreen.V131.Types.InputElmCode p0 p1

        Evergreen.V114.Types.UpdateNotebookTitle ->
            Evergreen.V131.Types.UpdateNotebookTitle

        Evergreen.V114.Types.NewNotebook ->
            Evergreen.V131.Types.NewNotebook

        Evergreen.V114.Types.ProposeDeletingNotebook ->
            Evergreen.V131.Types.ProposeDeletingNotebook

        Evergreen.V114.Types.CancelDeleteNotebook ->
            Evergreen.V131.Types.CancelDeleteNotebook

        Evergreen.V114.Types.ChangeAppMode p0 ->
            Evergreen.V131.Types.ChangeAppMode (p0 |> migrate_Types_AppMode)

        Evergreen.V114.Types.SetClock p0 ->
            Evergreen.V131.Types.SetClock (p0 |> migrate_Types_ClockState)

        Evergreen.V114.Types.Reset ->
            Evergreen.V131.Types.Reset

        Evergreen.V114.Types.TogglePublic ->
            Evergreen.V131.Types.TogglePublic

        Evergreen.V114.Types.SetCurrentNotebook p0 ->
            Evergreen.V131.Types.SetCurrentNotebook (p0 |> migrate_Notebook_Book_Book)

        Evergreen.V114.Types.CloneNotebook ->
            Evergreen.V131.Types.CloneNotebook

        Evergreen.V114.Types.PullNotebook ->
            Evergreen.V131.Types.PullNotebook

        Evergreen.V114.Types.ExportNotebook ->
            Evergreen.V131.Types.ExportNotebook

        Evergreen.V114.Types.SetShowNotebooksState p0 ->
            Evergreen.V131.Types.SetShowNotebooksState (p0 |> migrate_Types_ShowNotebooks)

        Evergreen.V114.Types.DuplicateNotebook ->
            Evergreen.V131.Types.DuplicateNotebook

        Evergreen.V114.Types.ImportRequested ->
            Evergreen.V131.Types.ImportRequested

        Evergreen.V114.Types.ImportSelected p0 ->
            Evergreen.V131.Types.ImportSelected p0

        Evergreen.V114.Types.ImportLoaded p0 ->
            Evergreen.V131.Types.ImportLoaded p0

        Evergreen.V114.Types.ChangePopup p0 ->
            Evergreen.V131.Types.ChangePopup (p0 |> migrate_Types_PopupState)

        Evergreen.V114.Types.GotViewport p0 ->
            Evergreen.V131.Types.GotViewport p0

        Evergreen.V114.Types.GotNewWindowDimensions p0 p1 ->
            Evergreen.V131.Types.GotNewWindowDimensions p0 p1

        Evergreen.V114.Types.SignUp ->
            Evergreen.V131.Types.SignUp

        Evergreen.V114.Types.SignIn ->
            Evergreen.V131.Types.SignIn

        Evergreen.V114.Types.SignOut ->
            Evergreen.V131.Types.SignOut

        Evergreen.V114.Types.SetSignupState p0 ->
            Evergreen.V131.Types.SetSignupState (p0 |> migrate_Types_SignupState)

        Evergreen.V114.Types.InputUsername p0 ->
            Evergreen.V131.Types.InputUsername p0

        Evergreen.V114.Types.InputSignupUsername p0 ->
            Evergreen.V131.Types.InputSignupUsername p0

        Evergreen.V114.Types.InputPassword p0 ->
            Evergreen.V131.Types.InputPassword p0

        Evergreen.V114.Types.InputPasswordAgain p0 ->
            Evergreen.V131.Types.InputPasswordAgain p0

        Evergreen.V114.Types.InputEmail p0 ->
            Evergreen.V131.Types.InputEmail p0

        Evergreen.V114.Types.InputTitle p0 ->
            Evergreen.V131.Types.InputTitle p0

        Evergreen.V114.Types.InputCloneReference p0 ->
            Evergreen.V131.Types.InputCloneReference p0

        Evergreen.V114.Types.AdminRunTask ->
            Evergreen.V131.Types.AdminRunTask

        Evergreen.V114.Types.GetUsers ->
            Evergreen.V131.Types.GetUsers


migrate_Types_Message : Evergreen.V114.Types.Message -> Evergreen.V131.Types.Message
migrate_Types_Message old =
    { id = old.id
    , txt = old.txt
    , status = old.status |> migrate_Types_MessageStatus
    }


migrate_Types_MessageStatus : Evergreen.V114.Types.MessageStatus -> Evergreen.V131.Types.MessageStatus
migrate_Types_MessageStatus old =
    case old of
        Evergreen.V114.Types.MSWhite ->
            Evergreen.V131.Types.MSWhite

        Evergreen.V114.Types.MSYellow ->
            Evergreen.V131.Types.MSYellow

        Evergreen.V114.Types.MSBlue ->
            Evergreen.V131.Types.MSBlue

        Evergreen.V114.Types.MSRed ->
            Evergreen.V131.Types.MSRed


migrate_Types_NoteBookDict : Evergreen.V114.Types.NoteBookDict -> Evergreen.V131.Types.NoteBookDict
migrate_Types_NoteBookDict old =
    old |> Dict.map (\k -> migrate_Notebook_Book_Book)


migrate_Types_PopupState : Evergreen.V114.Types.PopupState -> Evergreen.V131.Types.PopupState
migrate_Types_PopupState old =
    case old of
        Evergreen.V114.Types.NoPopup ->
            Evergreen.V131.Types.NoPopup

        Evergreen.V114.Types.AdminPopup ->
            Evergreen.V131.Types.AdminPopup

        Evergreen.V114.Types.ManualPopup ->
            Evergreen.V131.Types.ManualPopup

        Evergreen.V114.Types.NewDataSetPopup ->
            Evergreen.V131.Types.NewDataSetPopup

        Evergreen.V114.Types.EditDataSetPopup p0 ->
            Evergreen.V131.Types.EditDataSetPopup (p0 |> migrate_Notebook_DataSet_DataSetMetaData)

        Evergreen.V114.Types.SignUpPopup ->
            Evergreen.V131.Types.SignUpPopup

        Evergreen.V114.Types.PackageListPopup ->
            Evergreen.V131.Types.PackageListPopup

        Evergreen.V114.Types.CLIPopup ->
            Evergreen.V131.Types.CLIPopup

        Evergreen.V114.Types.NewNotebookPopup ->
            Evergreen.V131.Types.NewNotebookPopup

        Evergreen.V114.Types.StateEditorPopup ->
            Evergreen.V131.Types.StateEditorPopup

        Evergreen.V114.Types.ViewPublicDataSetsPopup ->
            Evergreen.V131.Types.ViewPublicDataSetsPopup

        Evergreen.V114.Types.ViewPrivateDataSetsPopup ->
            Evergreen.V131.Types.ViewPrivateDataSetsPopup


migrate_Types_ShowNotebooks : Evergreen.V114.Types.ShowNotebooks -> Evergreen.V131.Types.ShowNotebooks
migrate_Types_ShowNotebooks old =
    case old of
        Evergreen.V114.Types.ShowUserNotebooks ->
            Evergreen.V131.Types.ShowUserNotebooks

        Evergreen.V114.Types.ShowPublicNotebooks ->
            Evergreen.V131.Types.ShowPublicNotebooks


migrate_Types_SignupState : Evergreen.V114.Types.SignupState -> Evergreen.V131.Types.SignupState
migrate_Types_SignupState old =
    case old of
        Evergreen.V114.Types.ShowSignUpForm ->
            Evergreen.V131.Types.ShowSignUpForm

        Evergreen.V114.Types.HideSignUpForm ->
            Evergreen.V131.Types.HideSignUpForm


migrate_Types_ToBackend : Evergreen.V114.Types.ToBackend -> Evergreen.V131.Types.ToBackend
migrate_Types_ToBackend old =
    case old of
        Evergreen.V114.Types.NoOpToBackend ->
            Evergreen.V131.Types.NoOpToBackend

        Evergreen.V114.Types.GetRandomSeed ->
            Evergreen.V131.Types.GetRandomSeed

        Evergreen.V114.Types.RunTask ->
            Evergreen.V131.Types.RunTask

        Evergreen.V114.Types.SendUsers ->
            Evergreen.V131.Types.SendUsers

        Evergreen.V114.Types.DeleteDataSet p0 ->
            Evergreen.V131.Types.DeleteDataSet (p0 |> migrate_Notebook_DataSet_DataSetMetaData)

        Evergreen.V114.Types.SaveDataSet p0 ->
            Evergreen.V131.Types.SaveDataSet (p0 |> migrate_Notebook_DataSet_DataSetMetaData)

        Evergreen.V114.Types.GetListOfDataSets p0 ->
            Evergreen.V131.Types.GetListOfDataSets (p0 |> migrate_Types_DataSetDescription)

        Evergreen.V114.Types.CreateDataSet p0 ->
            Evergreen.V131.Types.CreateDataSet (p0 |> migrate_Notebook_DataSet_DataSet)

        Evergreen.V114.Types.GetData p0 p1 p2 ->
            Evergreen.V131.Types.GetData p0 p1 p2

        Evergreen.V114.Types.GetDataSetForDownload p0 ->
            Evergreen.V131.Types.GetDataSetForDownload p0

        Evergreen.V114.Types.GetCellsToInclude p0 ->
            Evergreen.V131.Types.GetCellsToInclude p0

        Evergreen.V114.Types.SaveElmJsonDependenciesBE p0 p1 ->
            Evergreen.V131.Types.SaveElmJsonDependenciesBE p0 p1

        Evergreen.V114.Types.CreateNotebook p0 p1 ->
            Evergreen.V131.Types.CreateNotebook p0 p1

        Evergreen.V114.Types.ImportNewBook p0 p1 ->
            Evergreen.V131.Types.ImportNewBook p0 (p1 |> migrate_Notebook_Book_Book)

        Evergreen.V114.Types.SaveNotebook p0 ->
            Evergreen.V131.Types.SaveNotebook (p0 |> migrate_Notebook_Book_Book)

        Evergreen.V114.Types.DeleteNotebook p0 ->
            Evergreen.V131.Types.DeleteNotebook (p0 |> migrate_Notebook_Book_Book)

        Evergreen.V114.Types.GetPublicNotebook p0 ->
            Evergreen.V131.Types.GetPublicNotebook p0

        Evergreen.V114.Types.GetClonedNotebook p0 p1 p2 ->
            Evergreen.V131.Types.GetClonedNotebook p0 p1 p2

        Evergreen.V114.Types.GetPulledNotebook p0 p1 p2 p3 ->
            Evergreen.V131.Types.GetPulledNotebook p0 p1 p2 p3

        Evergreen.V114.Types.UpdateSlugDict p0 ->
            Evergreen.V131.Types.UpdateSlugDict (p0 |> migrate_Notebook_Book_Book)

        Evergreen.V114.Types.GetUsersNotebooks p0 ->
            Evergreen.V131.Types.GetUsersNotebooks p0

        Evergreen.V114.Types.GetPublicNotebooks p0 p1 ->
            Evergreen.V131.Types.GetPublicNotebooks (p0 |> Maybe.map migrate_Notebook_Book_Book) p1

        Evergreen.V114.Types.SignUpBE p0 p1 p2 ->
            Evergreen.V131.Types.SignUpBE p0 p1 p2

        Evergreen.V114.Types.SignInBEDev ->
            Evergreen.V131.Types.SignInBEDev

        Evergreen.V114.Types.SignInBE p0 p1 ->
            Evergreen.V131.Types.SignInBE p0 p1

        Evergreen.V114.Types.SignOutBE p0 ->
            Evergreen.V131.Types.SignOutBE p0

        Evergreen.V114.Types.UpdateUserWith p0 ->
            Evergreen.V131.Types.UpdateUserWith (p0 |> migrate_User_User)


migrate_Types_ToFrontend : Evergreen.V114.Types.ToFrontend -> Evergreen.V131.Types.ToFrontend
migrate_Types_ToFrontend old =
    case old of
        Evergreen.V114.Types.NoOpToFrontend ->
            Evergreen.V131.Types.NoOpToFrontend

        Evergreen.V114.Types.MessageReceived p0 ->
            Evergreen.V131.Types.MessageReceived (p0 |> migrate_Types_Message)

        Evergreen.V114.Types.GotRandomSeed p0 ->
            Evergreen.V131.Types.GotRandomSeed p0

        Evergreen.V114.Types.GotUsers p0 ->
            Evergreen.V131.Types.GotUsers p0

        Evergreen.V114.Types.GotListOfPublicDataSets p0 ->
            Evergreen.V131.Types.GotListOfPublicDataSets p0

        Evergreen.V114.Types.GotListOfPrivateDataSets p0 ->
            Evergreen.V131.Types.GotListOfPrivateDataSets p0

        Evergreen.V114.Types.GotData p0 p1 p2 ->
            Evergreen.V131.Types.GotData p0 p1 (p2 |> migrate_Notebook_DataSet_DataSet)

        Evergreen.V114.Types.GotDataForDownload p0 ->
            Evergreen.V131.Types.GotDataForDownload (p0 |> migrate_Notebook_DataSet_DataSet)

        Evergreen.V114.Types.GotCellsToInclude p0 ->
            Evergreen.V131.Types.GotCellsToInclude (p0 |> List.map migrate_Notebook_Cell_Cell)

        Evergreen.V114.Types.GotPackageDict p0 ->
            Evergreen.V131.Types.GotPackageDict p0

        Evergreen.V114.Types.GotNotebook p0 ->
            Evergreen.V131.Types.GotNotebook (p0 |> migrate_Notebook_Book_Book)

        Evergreen.V114.Types.GotPublicNotebook p0 ->
            Evergreen.V131.Types.GotPublicNotebook (p0 |> migrate_Notebook_Book_Book)

        Evergreen.V114.Types.GotNotebooks p0 p1 ->
            Evergreen.V131.Types.GotNotebooks (p0 |> Maybe.map migrate_Notebook_Book_Book)
                (p1 |> List.map migrate_Notebook_Book_Book)

        Evergreen.V114.Types.SendMessage p0 ->
            Evergreen.V131.Types.SendMessage p0

        Evergreen.V114.Types.UserSignedIn p0 p1 ->
            Evergreen.V131.Types.UserSignedIn (p0 |> migrate_User_User) p1

        Evergreen.V114.Types.SendUser p0 ->
            Evergreen.V131.Types.SendUser (p0 |> migrate_User_User)


migrate_Types_UserToNotebookDict : Evergreen.V114.Types.UserToNotebookDict -> Evergreen.V131.Types.UserToNotebookDict
migrate_Types_UserToNotebookDict old =
    old |> Dict.map (\k -> migrate_Types_NoteBookDict)


migrate_User_User : Evergreen.V114.User.User -> Evergreen.V131.User.User
migrate_User_User old =
    old
