module Evergreen.Migrate.V145 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import BiDict
import Dict
import Evergreen.V140.Authentication
import Evergreen.V140.Credentials
import Evergreen.V140.Notebook.Book
import Evergreen.V140.Notebook.Cell
import Evergreen.V140.Notebook.Types
import Evergreen.V140.Types
import Evergreen.V140.User
import Evergreen.V145.Authentication
import Evergreen.V145.Credentials
import Evergreen.V145.Notebook.Book
import Evergreen.V145.Notebook.Cell
import Evergreen.V145.Notebook.Types
import Evergreen.V145.Types
import Evergreen.V145.User
import Lamdera.Migrations exposing (..)
import List
import Maybe


frontendModel : Evergreen.V140.Types.FrontendModel -> ModelMigration Evergreen.V145.Types.FrontendModel Evergreen.V145.Types.FrontendMsg
frontendModel old =
    ModelUnchanged


backendModel : Evergreen.V140.Types.BackendModel -> ModelMigration Evergreen.V145.Types.BackendModel Evergreen.V145.Types.BackendMsg
backendModel old =
    ModelMigrated ( migrate_Types_BackendModel old, Cmd.none )


frontendMsg : Evergreen.V140.Types.FrontendMsg -> MsgMigration Evergreen.V145.Types.FrontendMsg Evergreen.V145.Types.FrontendMsg
frontendMsg old =
    MsgUnchanged


toBackend : Evergreen.V140.Types.ToBackend -> MsgMigration Evergreen.V145.Types.ToBackend Evergreen.V145.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V140.Types.BackendMsg -> MsgMigration Evergreen.V145.Types.BackendMsg Evergreen.V145.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V140.Types.ToFrontend -> MsgMigration Evergreen.V145.Types.ToFrontend Evergreen.V145.Types.FrontendMsg
toFrontend old =
    MsgUnchanged


migrate_Types_BackendModel : Evergreen.V140.Types.BackendModel -> Evergreen.V145.Types.BackendModel
migrate_Types_BackendModel old =
    { currentTime = old.currentTime
    , randomSeed = old.randomSeed
    , uuidCount = old.uuidCount
    , uuid = old.uuid
    , randomAtmosphericInt = old.randomAtmosphericInt
    , dataSetLibrary = old.dataSetLibrary
    , userToNoteBookDict = old.userToNoteBookDict |> migrate_Types_UserToNotebookDict
    , usernameToPackageDictDict = old.usernameToPackageDictDict
    , slugDict = old.slugDict
    , sessions = BiDict.empty
    , sessionInfo = Dict.empty
    , authenticationDict = old.authenticationDict |> migrate_Authentication_AuthenticationDict
    }


migrate_Authentication_AuthenticationDict : Evergreen.V140.Authentication.AuthenticationDict -> Evergreen.V145.Authentication.AuthenticationDict
migrate_Authentication_AuthenticationDict old =
    old |> Dict.map (\k -> migrate_Authentication_UserData)


migrate_Authentication_UserData : Evergreen.V140.Authentication.UserData -> Evergreen.V145.Authentication.UserData
migrate_Authentication_UserData old =
    { user = old.user |> migrate_User_User
    , credentials = old.credentials |> migrate_Credentials_Credentials
    }


migrate_Credentials_Credentials : Evergreen.V140.Credentials.Credentials -> Evergreen.V145.Credentials.Credentials
migrate_Credentials_Credentials old =
    case old of
        Evergreen.V140.Credentials.V1 p0 p1 ->
            Evergreen.V145.Credentials.V1 p0 p1


migrate_Notebook_Book_Book : Evergreen.V140.Notebook.Book.Book -> Evergreen.V145.Notebook.Book.Book
migrate_Notebook_Book_Book old =
    { id = old.id
    , dirty = old.dirty
    , slug = old.slug
    , origin = old.origin
    , author = old.author
    , createdAt = old.createdAt
    , updatedAt = old.updatedAt
    , public = old.public
    , title = old.title
    , cells = old.cells |> List.map migrate_Notebook_Cell_Cell
    , currentIndex = old.currentIndex
    , packageNames = old.packageNames
    , tags = old.tags
    , options = old.options
    }


migrate_Notebook_Cell_Cell : Evergreen.V140.Notebook.Cell.Cell -> Evergreen.V145.Notebook.Cell.Cell
migrate_Notebook_Cell_Cell old =
    { index = old.index
    , text = old.text
    , tipe = old.tipe |> migrate_Notebook_Cell_CellType
    , value = old.value |> migrate_Notebook_Cell_CellValue
    , cellState = old.cellState |> migrate_Notebook_Cell_CellState
    , commented = old.commented
    , locked = old.locked
    , report = old.report |> Tuple.mapSecond (Maybe.map (List.map migrate_Notebook_Types_MessageItem))
    , replData = old.replData
    , highlightTime = old.highlightTime
    }


migrate_Notebook_Cell_CellState : Evergreen.V140.Notebook.Cell.CellState -> Evergreen.V145.Notebook.Cell.CellState
migrate_Notebook_Cell_CellState old =
    case old of
        Evergreen.V140.Notebook.Cell.CSEdit ->
            Evergreen.V145.Notebook.Cell.CSEdit

        Evergreen.V140.Notebook.Cell.CSView ->
            Evergreen.V145.Notebook.Cell.CSView


migrate_Notebook_Cell_CellType : Evergreen.V140.Notebook.Cell.CellType -> Evergreen.V145.Notebook.Cell.CellType
migrate_Notebook_Cell_CellType old =
    case old of
        Evergreen.V140.Notebook.Cell.CTCode ->
            Evergreen.V145.Notebook.Cell.CTCode

        Evergreen.V140.Notebook.Cell.CTMarkdown ->
            Evergreen.V145.Notebook.Cell.CTMarkdown


migrate_Notebook_Cell_CellValue : Evergreen.V140.Notebook.Cell.CellValue -> Evergreen.V145.Notebook.Cell.CellValue
migrate_Notebook_Cell_CellValue old =
    case old of
        Evergreen.V140.Notebook.Cell.CVString p0 ->
            Evergreen.V145.Notebook.Cell.CVString p0

        Evergreen.V140.Notebook.Cell.CVMarkdown p0 ->
            Evergreen.V145.Notebook.Cell.CVMarkdown p0

        Evergreen.V140.Notebook.Cell.CVNone ->
            Evergreen.V145.Notebook.Cell.CVNone


migrate_Notebook_Types_MessageItem : Evergreen.V140.Notebook.Types.MessageItem -> Evergreen.V145.Notebook.Types.MessageItem
migrate_Notebook_Types_MessageItem old =
    case old of
        Evergreen.V140.Notebook.Types.Plain p0 ->
            Evergreen.V145.Notebook.Types.Plain p0

        Evergreen.V140.Notebook.Types.Styled p0 ->
            Evergreen.V145.Notebook.Types.Styled (p0 |> migrate_Notebook_Types_StyledString)


migrate_Notebook_Types_StyledString : Evergreen.V140.Notebook.Types.StyledString -> Evergreen.V145.Notebook.Types.StyledString
migrate_Notebook_Types_StyledString old =
    old


migrate_Types_NoteBookDict : Evergreen.V140.Types.NoteBookDict -> Evergreen.V145.Types.NoteBookDict
migrate_Types_NoteBookDict old =
    old |> Dict.map (\k -> migrate_Notebook_Book_Book)


migrate_Types_UserToNotebookDict : Evergreen.V140.Types.UserToNotebookDict -> Evergreen.V145.Types.UserToNotebookDict
migrate_Types_UserToNotebookDict old =
    old |> Dict.map (\k -> migrate_Types_NoteBookDict)


migrate_User_User : Evergreen.V140.User.User -> Evergreen.V145.User.User
migrate_User_User old =
    old
