module Evergreen.Migrate.V23 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Evergreen.V22.Notebook.Book
import Evergreen.V22.Notebook.Cell
import Evergreen.V22.Notebook.DataSet
import Evergreen.V22.Notebook.Types
import Evergreen.V22.Types
import Evergreen.V23.Notebook.Book
import Evergreen.V23.Notebook.Cell
import Evergreen.V23.Notebook.DataSet
import Evergreen.V23.Notebook.Types
import Evergreen.V23.Types
import Lamdera.Migrations exposing (..)
import List
import Maybe


frontendModel : Evergreen.V22.Types.FrontendModel -> ModelMigration Evergreen.V23.Types.FrontendModel Evergreen.V23.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V22.Types.BackendModel -> ModelMigration Evergreen.V23.Types.BackendModel Evergreen.V23.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V22.Types.FrontendMsg -> MsgMigration Evergreen.V23.Types.FrontendMsg Evergreen.V23.Types.FrontendMsg
frontendMsg old =
    MsgUnchanged


toBackend : Evergreen.V22.Types.ToBackend -> MsgMigration Evergreen.V23.Types.ToBackend Evergreen.V23.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V22.Types.BackendMsg -> MsgMigration Evergreen.V23.Types.BackendMsg Evergreen.V23.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V22.Types.ToFrontend -> MsgMigration Evergreen.V23.Types.ToFrontend Evergreen.V23.Types.FrontendMsg
toFrontend old =
    MsgUnchanged


migrate_Types_FrontendModel : Evergreen.V22.Types.FrontendModel -> Evergreen.V23.Types.FrontendModel
migrate_Types_FrontendModel old =
    { key = old.key
    , url = old.url
    , messages = old.messages |> List.map migrate_Types_Message
    , appState = old.appState |> migrate_Types_AppState
    , appMode = old.appMode |> migrate_Types_AppMode
    , currentTime = old.currentTime
    , tickCount = old.tickCount
    , clockState = old.clockState |> migrate_Types_ClockState
    , pressedKeys = old.pressedKeys
    , randomSeed = old.randomSeed
    , randomProbabilities = old.randomProbabilities
    , probabilityVectorLength = old.probabilityVectorLength
    , messageId = old.messageId
    , users = old.users
    , inputName = old.inputName
    , inputIdentifier = old.inputIdentifier
    , inputAuthor = old.inputAuthor
    , inputDescription = old.inputDescription
    , inputComments = old.inputComments
    , inputData = old.inputData
    , inputPackages = old.inputPackages
    , inputInitialStateValue = old.inputInitialStateValue
    , publicDataSetMetaDataList = old.publicDataSetMetaDataList
    , privateDataSetMetaDataList = old.privateDataSetMetaDataList
    , theme = old.theme |> migrate_Notebook_Book_Theme
    , evalState = old.evalState |> migrate_Notebook_Types_EvalState
    , packagesFromCompiler = old.packagesFromCompiler
    , packageDict = old.packageDict
    , elmJsonError = old.elmJsonError
    , kvDict = old.kvDict
    , books = old.books |> List.map migrate_Notebook_Book_Book
    , currentCell = old.currentCell |> Maybe.map migrate_Notebook_Cell_Cell
    , cellInsertionDirection = old.cellInsertionDirection |> migrate_Notebook_Types_CellDirection
    , currentBook = old.currentBook |> migrate_Notebook_Book_Book
    , cellContent = old.cellContent
    , currentCellIndex = old.currentCellIndex
    , cloneReference = old.cloneReference
    , deleteNotebookState = old.deleteNotebookState |> migrate_Types_DeleteNotebookState
    , showNotebooks = old.showNotebooks |> migrate_Types_ShowNotebooks
    , signupState = old.signupState |> migrate_Types_SignupState
    , currentUser = old.currentUser
    , inputUsername = old.inputUsername
    , inputSignupUsername = old.inputSignupUsername
    , inputEmail = old.inputEmail
    , inputRealname = old.inputRealname
    , inputPassword = old.inputPassword
    , inputPasswordAgain = old.inputPasswordAgain
    , inputTitle = old.inputTitle
    , windowWidth = old.windowWidth
    , windowHeight = old.windowHeight
    , popupState = old.popupState |> migrate_Types_PopupState
    , showEditor = old.showEditor
    }


migrate_Notebook_Book_Book : Evergreen.V22.Notebook.Book.Book -> Evergreen.V23.Notebook.Book.Book
migrate_Notebook_Book_Book old =
    { id = old.id
    , dirty = old.dirty
    , slug = old.slug
    , origin = old.origin
    , author = old.author
    , createdAt = old.createdAt
    , updatedAt = old.updatedAt
    , public = old.public
    , title = old.title
    , cells = old.cells |> List.map migrate_Notebook_Cell_Cell
    , currentIndex = old.currentIndex
    , packageNames = old.packageNames
    , tags = old.tags
    , options = old.options
    }


migrate_Notebook_Book_Theme : Evergreen.V22.Notebook.Book.Theme -> Evergreen.V23.Notebook.Book.Theme
migrate_Notebook_Book_Theme old =
    case old of
        Evergreen.V22.Notebook.Book.DarkTheme ->
            Evergreen.V23.Notebook.Book.DarkTheme

        Evergreen.V22.Notebook.Book.LightTheme ->
            Evergreen.V23.Notebook.Book.LightTheme


migrate_Notebook_Cell_Cell : Evergreen.V22.Notebook.Cell.Cell -> Evergreen.V23.Notebook.Cell.Cell
migrate_Notebook_Cell_Cell old =
    { index = old.index
    , text = old.text
    , tipe = old.tipe |> migrate_Notebook_Cell_CellType
    , value = old.value |> migrate_Notebook_Cell_CellValue
    , cellState = old.cellState |> migrate_Notebook_Cell_CellState
    , locked = old.locked
    , report = old.report |> Maybe.map (List.map migrate_Notebook_Types_MessageItem)
    , replData = old.replData
    }


migrate_Notebook_Cell_CellState : Evergreen.V22.Notebook.Cell.CellState -> Evergreen.V23.Notebook.Cell.CellState
migrate_Notebook_Cell_CellState old =
    case old of
        Evergreen.V22.Notebook.Cell.CSEdit ->
            Evergreen.V23.Notebook.Cell.CSEdit

        Evergreen.V22.Notebook.Cell.CSView ->
            Evergreen.V23.Notebook.Cell.CSView


migrate_Notebook_Cell_CellType : Evergreen.V22.Notebook.Cell.CellType -> Evergreen.V23.Notebook.Cell.CellType
migrate_Notebook_Cell_CellType old =
    case old of
        Evergreen.V22.Notebook.Cell.CTCode ->
            Evergreen.V23.Notebook.Cell.CTCode

        Evergreen.V22.Notebook.Cell.CTMarkdown ->
            Evergreen.V23.Notebook.Cell.CTMarkdown


migrate_Notebook_Cell_CellValue : Evergreen.V22.Notebook.Cell.CellValue -> Evergreen.V23.Notebook.Cell.CellValue
migrate_Notebook_Cell_CellValue old =
    case old of
        Evergreen.V22.Notebook.Cell.CVString p0 ->
            Evergreen.V23.Notebook.Cell.CVString p0

        Evergreen.V22.Notebook.Cell.CVMarkdown p0 ->
            Evergreen.V23.Notebook.Cell.CVMarkdown p0

        Evergreen.V22.Notebook.Cell.CVNone ->
            Evergreen.V23.Notebook.Cell.CVNone


migrate_Notebook_DataSet_DataSetMetaData : Evergreen.V22.Notebook.DataSet.DataSetMetaData -> Evergreen.V23.Notebook.DataSet.DataSetMetaData
migrate_Notebook_DataSet_DataSetMetaData old =
    old


migrate_Notebook_Types_CellDirection : Evergreen.V22.Notebook.Types.CellDirection -> Evergreen.V23.Notebook.Types.CellDirection
migrate_Notebook_Types_CellDirection old =
    case old of
        Evergreen.V22.Notebook.Types.Up ->
            Evergreen.V23.Notebook.Types.Up

        Evergreen.V22.Notebook.Types.Down ->
            Evergreen.V23.Notebook.Types.Down


migrate_Notebook_Types_EvalState : Evergreen.V22.Notebook.Types.EvalState -> Evergreen.V23.Notebook.Types.EvalState
migrate_Notebook_Types_EvalState old =
    old


migrate_Notebook_Types_MessageItem : Evergreen.V22.Notebook.Types.MessageItem -> Evergreen.V23.Notebook.Types.MessageItem
migrate_Notebook_Types_MessageItem old =
    case old of
        Evergreen.V22.Notebook.Types.Plain p0 ->
            Evergreen.V23.Notebook.Types.Plain p0

        Evergreen.V22.Notebook.Types.Styled p0 ->
            Evergreen.V23.Notebook.Types.Styled (p0 |> migrate_Notebook_Types_StyledString)


migrate_Notebook_Types_StyledString : Evergreen.V22.Notebook.Types.StyledString -> Evergreen.V23.Notebook.Types.StyledString
migrate_Notebook_Types_StyledString old =
    old


migrate_Types_AppMode : Evergreen.V22.Types.AppMode -> Evergreen.V23.Types.AppMode
migrate_Types_AppMode old =
    case old of
        Evergreen.V22.Types.AMWorking ->
            Evergreen.V23.Types.AMWorking

        Evergreen.V22.Types.AMEditTitle ->
            Evergreen.V23.Types.AMEditTitle


migrate_Types_AppState : Evergreen.V22.Types.AppState -> Evergreen.V23.Types.AppState
migrate_Types_AppState old =
    case old of
        Evergreen.V22.Types.Loading ->
            Evergreen.V23.Types.Loading

        Evergreen.V22.Types.Loaded ->
            Evergreen.V23.Types.Loaded


migrate_Types_ClockState : Evergreen.V22.Types.ClockState -> Evergreen.V23.Types.ClockState
migrate_Types_ClockState old =
    case old of
        Evergreen.V22.Types.ClockRunning ->
            Evergreen.V23.Types.ClockRunning

        Evergreen.V22.Types.ClockStopped ->
            Evergreen.V23.Types.ClockStopped

        Evergreen.V22.Types.ClockPaused ->
            Evergreen.V23.Types.ClockPaused


migrate_Types_DeleteNotebookState : Evergreen.V22.Types.DeleteNotebookState -> Evergreen.V23.Types.DeleteNotebookState
migrate_Types_DeleteNotebookState old =
    case old of
        Evergreen.V22.Types.WaitingToDeleteNotebook ->
            Evergreen.V23.Types.WaitingToDeleteNotebook

        Evergreen.V22.Types.CanDeleteNotebook ->
            Evergreen.V23.Types.CanDeleteNotebook


migrate_Types_Message : Evergreen.V22.Types.Message -> Evergreen.V23.Types.Message
migrate_Types_Message old =
    { id = old.id
    , txt = old.txt
    , status = old.status |> migrate_Types_MessageStatus
    }


migrate_Types_MessageStatus : Evergreen.V22.Types.MessageStatus -> Evergreen.V23.Types.MessageStatus
migrate_Types_MessageStatus old =
    case old of
        Evergreen.V22.Types.MSWhite ->
            Evergreen.V23.Types.MSWhite

        Evergreen.V22.Types.MSYellow ->
            Evergreen.V23.Types.MSYellow

        Evergreen.V22.Types.MSGreen ->
            Evergreen.V23.Types.MSGreen

        Evergreen.V22.Types.MSRed ->
            Evergreen.V23.Types.MSRed


migrate_Types_PopupState : Evergreen.V22.Types.PopupState -> Evergreen.V23.Types.PopupState
migrate_Types_PopupState old =
    case old of
        Evergreen.V22.Types.NoPopup ->
            Evergreen.V23.Types.NoPopup

        Evergreen.V22.Types.AdminPopup ->
            Evergreen.V23.Types.AdminPopup

        Evergreen.V22.Types.ManualPopup ->
            Evergreen.V23.Types.ManualPopup

        Evergreen.V22.Types.NewDataSetPopup ->
            Evergreen.V23.Types.NewDataSetPopup

        Evergreen.V22.Types.EditDataSetPopup p0 ->
            Evergreen.V23.Types.EditDataSetPopup (p0 |> migrate_Notebook_DataSet_DataSetMetaData)

        Evergreen.V22.Types.SignUpPopup ->
            Evergreen.V23.Types.SignUpPopup

        Evergreen.V22.Types.PackageListPopup ->
            Evergreen.V23.Types.PackageListPopup

        Evergreen.V22.Types.NewNotebookPopup ->
            Evergreen.V23.Types.NewNotebookPopup

        Evergreen.V22.Types.StateEditorPopup ->
            Evergreen.V23.Types.StateEditorPopup

        Evergreen.V22.Types.ViewPublicDataSetsPopup ->
            Evergreen.V23.Types.ViewPublicDataSetsPopup

        Evergreen.V22.Types.ViewPrivateDataSetsPopup ->
            Evergreen.V23.Types.ViewPrivateDataSetsPopup


migrate_Types_ShowNotebooks : Evergreen.V22.Types.ShowNotebooks -> Evergreen.V23.Types.ShowNotebooks
migrate_Types_ShowNotebooks old =
    case old of
        Evergreen.V22.Types.ShowUserNotebooks ->
            Evergreen.V23.Types.ShowUserNotebooks

        Evergreen.V22.Types.ShowPublicNotebooks ->
            Evergreen.V23.Types.ShowPublicNotebooks


migrate_Types_SignupState : Evergreen.V22.Types.SignupState -> Evergreen.V23.Types.SignupState
migrate_Types_SignupState old =
    case old of
        Evergreen.V22.Types.ShowSignUpForm ->
            Evergreen.V23.Types.ShowSignUpForm

        Evergreen.V22.Types.HideSignUpForm ->
            Evergreen.V23.Types.HideSignUpForm
